from enum import Enum


MUSLIMPRO_URL = "https://www.muslimpro.com/find"
GEOCODE_URL = "https://positionstack.com/geo_api.php"
# Indonesian Based
RAMADHAN_API_INDONESIA = "https://calendarific.com/holiday/indonesia/idul-fitri"


class CalculationMethod(Enum):
    DEFAULT = "Precalc"
    ALGERIAN_MINISTER_OF_RELIGIOUS_AND_WAKFS = "Algeria"
    DIYANET_İŞLERI_BAŞKANLIĞI = "Diyanet"
    EGYPTIAN_GENERAL_AUTHORITY = "Egypt"
    EGYPTIAN_GENERAL_AUTHORITY_BIS = "EgyptBis"
    FIXED_ISHA_ANGLE_INTERVAL = "FixedIsha"
    FRANCE_UOIF_ANGLE_12DEG = "UOIF"
    FRANCE_ANGLE_15DEG = "Fr15"
    FRANCE_ANGLE_18DEG = "Fr18"
    ISLAMIC_UNIVERSITY_KARACHI = "Karachi"
    JAKIM_JABATAN_KEMAJUAN_ISLAM_MALAYSIA = "JAKIM"
    LONDON_UNIFIED_ISLAMIC_PRAYER_TIMETABLE = "UIPTL"
    MUIS_MAJLIS_UGAMA_ISLAM_SINGAPURA = "MUIS"
    MUSLIM_WORLD_LEAGUE_MWL = "MWL"
    NORTH_AMERICA_ISNA = "ISNA"
    SHIA_ITHNA_ASHARI_JAFARI = "Jafari"
    SIHAT_KEMENAG_KEMENTERIAN_AGAMA_RI = "KEMENAG"
    TUNISIAN_MINISTRY_OF_RELIGIOUS_AFFAIRS = "Tunisia"
    UAE_GENERAL_AUTHORITY_OF_ISLAMIC_AFFAIRS_AND_ENDOWMENTS = "AwqafUAE"
    UMM_AL_QURA_MAKKAH = "Makkah"
    UNIVERSITY_OF_TEHRAN = "Tehran"
    FEDERATION_OF_ISLAMIC_ASSOCIATIONS_IN_BASQUE_COUNTRY = "BASQUE"


class AsrjuristicMethod(Enum):
    STANDARD_SHAFI_MALIKI_HANBALI = "Standard"
    HANAFI = "Hanafi"
